--\SmartFinance\database_engine\src\main\resources\db\migration\V18__transaction_notr.sql
CREATE SEQUENCE IF NOT EXISTS SEQ_TRANSACTION_NOTR;
CREATE TABLE TRANSACTION_NOTR(
ID BIGINT DEFAULT SEQ_TRANSACTION_NOTR.NEXTVAL PRIMARY KEY,
TRANSACTION_NUMBER VARCHAR(14) NOT NULL,--20160707121201 which 2016-July-07 12:12:01
ACCOUNT_ID BIGINT,
INVOICE_ID BIGINT,
DATEUNIT_UNITDAY BIGINT,
COMMENT VARCHAR(512),
DEBIT_AMOUNT DECIMAL(10,4) DEFAULT 0,
CREDIT_AMOUNT DECIMAL(10,4) DEFAULT 0,
T_CREATEDON TIMESTAMP,
T_UPDATEDON TIMESTAMP,
FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ID),
FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE_NOTR(ID),
FOREIGN KEY (DATEUNIT_UNITDAY) REFERENCES DATEUNIT(UNITDAY)
);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_UNQ_TRNSCTN_TRNSCTNNMBR1 ON TRANSACTION_NOTR(TRANSACTION_NUMBER);--for equals/hashcode TRANSACTION_NUMBER

CREATE TRIGGER T_TRANSACTION_NOTR_INS
BEFORE INSERT
ON TRANSACTION_NOTR
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerTransaction";

CREATE TRIGGER T_TRANSACTION_NOTR_UPD
BEFORE UPDATE
ON TRANSACTION_NOTR
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerTransaction";

CREATE TRIGGER T_TRANSACTION_NOTR_DEL
BEFORE DELETE
ON TRANSACTION_NOTR
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerTransaction";

GRANT SELECT, INSERT, UPDATE, DELETE ON
TRANSACTION_NOTR
TO client;