CREATE USER IF NOT EXISTS client PASSWORD 'qwerty1234';

GRANT SELECT, INSERT ON
_DELETED_ROWS,
DATEUNIT
TO client;

GRANT SELECT, INSERT, UPDATE, DELETE ON
CURRENCY,
FAMILY_MEMBER,
ORGANIZATION,
CATEGORY_GROUP,
CATEGORY,
ACCOUNT_GROUP,
ACCOUNT
TO client;