--http://viralpatel.net/blogs/hibernate-self-join-annotation-mapping-many-to-many-example/
CREATE TABLE CHILD_TAX(
TAX_ID BIGINT NOT NULL,
CHILD_TAX_ID BIGINT NOT NULL,
T_CREATEDON TIMESTAMP,
T_UPDATEDON TIMESTAMP,
PRIMARY KEY(TAX_ID, CHILD_TAX_ID),
FOREIGN KEY (TAX_ID) REFERENCES TAX(ID),
FOREIGN KEY (CHILD_TAX_ID) REFERENCES TAX(ID)
);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_UNQ_TX_DCHLDD ON CHILD_TAX(TAX_ID,CHILD_TAX_ID);

CREATE TRIGGER T_CHILD_TAX_INS
BEFORE INSERT
ON CHILD_TAX
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerChildTax";

CREATE TRIGGER T_CHILD_TAX_UPD
BEFORE UPDATE
ON CHILD_TAX
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerChildTax";

CREATE TRIGGER T_CHILD_TAX_DEL
BEFORE DELETE
ON CHILD_TAX
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerChildTax";

GRANT SELECT, INSERT, UPDATE, DELETE ON
CHILD_TAX
TO client;