CREATE SEQUENCE IF NOT EXISTS SEQ_INVOICE;
CREATE TABLE INVOICE(
ID BIGINT DEFAULT SEQ_INVOICE.NEXTVAL PRIMARY KEY,
ORGANIZATION_ID BIGINT,
DATEUNIT_UNITDAY BIGINT,
COMMENT VARCHAR(512) NOT NULL,
SUB_TOTAL DECIMAL(10,4) DEFAULT 0, --before tax
TOTAL DECIMAL(10,4) DEFAULT 0, --after tax
T_CREATEDON TIMESTAMP,
T_UPDATEDON TIMESTAMP,
FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION(ID),
FOREIGN KEY (DATEUNIT_UNITDAY) REFERENCES DATEUNIT(UNITDAY)
);

CREATE TRIGGER T_INVOICE_INS
BEFORE INSERT
ON INVOICE
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerInvoice";

CREATE TRIGGER T_INVOICE_UPD
BEFORE UPDATE
ON INVOICE
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerInvoice";

CREATE TRIGGER T_INVOICE_DEL
BEFORE DELETE
ON INVOICE
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerInvoice";

GRANT SELECT, INSERT, UPDATE, DELETE ON
INVOICE
TO client;