CREATE SEQUENCE IF NOT EXISTS SEQ_INVOICE;
CREATE TABLE INVOICE(
ID BIGINT DEFAULT SEQ_INVOICE.NEXTVAL PRIMARY KEY,
ORGANIZATION_ID BIGINT,
COMMENT VARCHAR(512) NOT NULL,
BALANCE DECIMAL(10,4) DEFAULT 0,
T_CREATEDON TIMESTAMP,
T_UPDATEDON TIMESTAMP,
FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION(ID)
);

CREATE TRIGGER T_INVOICE_INS
BEFORE INSERT
ON INVOICE
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerInvoice";

CREATE TRIGGER T_INVOICE_UPD
BEFORE UPDATE
ON INVOICE
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerInvoice";

CREATE TRIGGER T_INVOICE_DEL
BEFORE DELETE
ON INVOICE
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerInvoice";

GRANT SELECT, INSERT, UPDATE, DELETE ON
INVOICE
TO client;