CREATE SEQUENCE IF NOT EXISTS SEQ_ITEM;
CREATE TABLE ITEM(
ID BIGINT DEFAULT SEQ_ITEM.NEXTVAL PRIMARY KEY,
ORDER_NUMBER INT, -- 1,2,3
INVOICE_ID BIGINT,
CATEGORY_ID BIGINT,
TAX_ID BIGINT,
FAMILY_MEMBER_ID BIGINT,
DATEUNIT_UNITDAY BIGINT,
DESCRIPTION1 VARCHAR(512) NOT NULL,
DESCRIPTION2 VARCHAR(512) NOT NULL,
COMMENT VARCHAR(512) NOT NULL,
SUB_TOTAL DECIMAL(10,4) DEFAULT 0, --before tax
TOTAL DECIMAL(10,4) DEFAULT 0, --after tax
T_CREATEDON TIMESTAMP,
T_UPDATEDON TIMESTAMP,
FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE(ID),
FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID),
FOREIGN KEY (TAX_ID) REFERENCES TAX(ID),
FOREIGN KEY (FAMILY_MEMBER_ID) REFERENCES FAMILY_MEMBER(ID),
FOREIGN KEY (DATEUNIT_UNITDAY) REFERENCES DATEUNIT(UNITDAY)
);

CREATE TRIGGER T_ITEM_INS
BEFORE INSERT
ON ITEM
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerItem";

CREATE TRIGGER T_ITEM_UPD
BEFORE UPDATE
ON ITEM
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerItem";

CREATE TRIGGER T_ITEM_DEL
BEFORE DELETE
ON ITEM
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerItem";

GRANT SELECT, INSERT, UPDATE, DELETE ON
ITEM
TO client;