CREATE SEQUENCE IF NOT EXISTS SEQ_TRANSACTION;
CREATE TABLE TRANSACTION(
ID BIGINT DEFAULT SEQ_TRANSACTION.NEXTVAL PRIMARY KEY,
TRANSACTION_NUMBER VARCHAR(14) NOT NULL,--20160707121201 which 2016-July-07 12:12:01
ACCOUNT_ID BIGINT,
ACCOUNT_GROUP_TYPE VARCHAR(1) NOT NULL,--discriminator: CREDIT/DEBIT account group
INVOICE_ID BIGINT,
DATEUNIT_UNITDAY BIGINT,
COMMENT VARCHAR(512) NOT NULL,
DEBIT_AMOUNT DECIMAL(10,4) DEFAULT 0,
CREDIT_AMOUNT DECIMAL(10,4) DEFAULT 0,
T_CREATEDON TIMESTAMP,
T_UPDATEDON TIMESTAMP,
FOREIGN KEY (ACCOUNT_ID,ACCOUNT_GROUP_TYPE) REFERENCES ACCOUNT(ID,ACCOUNT_GROUP_TYPE),
FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE(ID),
FOREIGN KEY (DATEUNIT_UNITDAY) REFERENCES DATEUNIT(UNITDAY)
);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_UNQ_TRNSCTN_TRNSCTNNMBR ON TRANSACTION(TRANSACTION_NUMBER);--for equals/hashcode TRANSACTION_NUMBER

CREATE TRIGGER T_TRANSACTION_INS
BEFORE INSERT
ON TRANSACTION
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerTransaction";

CREATE TRIGGER T_TRANSACTION_UPD
BEFORE UPDATE
ON TRANSACTION
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerTransaction";

CREATE TRIGGER T_TRANSACTION_DEL
BEFORE DELETE
ON TRANSACTION
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerTransaction";

GRANT SELECT, INSERT, UPDATE, DELETE ON
TRANSACTION
TO client;