--SmartFinance\database_engine\src\main\resources\db\migration\V16__invoice_notr.sql
CREATE SEQUENCE IF NOT EXISTS SEQ_INVOICE_NOTR;
CREATE TABLE INVOICE_NOTR(
ID BIGINT DEFAULT SEQ_INVOICE_NOTR.NEXTVAL PRIMARY KEY,
INVOICE_NUMBER VARCHAR(14) NOT NULL,--20160707121201 which 2016-July-07 12:12:01
ORGANIZATION_ID BIGINT,
DATEUNIT_UNITDAY BIGINT,
COMMENT VARCHAR(512) NOT NULL,
SUB_TOTAL DECIMAL(10,4) DEFAULT 0, --before tax
TOTAL DECIMAL(10,4) DEFAULT 0, --after tax
T_CREATEDON TIMESTAMP,
T_UPDATEDON TIMESTAMP,
FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION(ID),
FOREIGN KEY (DATEUNIT_UNITDAY) REFERENCES DATEUNIT(UNITDAY)
);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_UNQ_NVC_NVCNMBR1 ON INVOICE_NOTR(INVOICE_NUMBER);--for equals/hashcode INVOICE_NUMBER

CREATE TRIGGER T_INVOICE_NOTR_INS
BEFORE INSERT
ON INVOICE_NOTR
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerInvoiceNoTriggerTotals";

CREATE TRIGGER T_INVOICE_NOTR_UPD
BEFORE UPDATE
ON INVOICE_NOTR
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerInvoiceNoTriggerTotals";

CREATE TRIGGER T_INVOICE_NOTR_DEL
BEFORE DELETE
ON INVOICE_NOTR
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerInvoiceNoTriggerTotals";

GRANT SELECT, INSERT, UPDATE, DELETE ON
INVOICE_NOTR
TO client;