CREATE OR REPLACE VIEW V_CUM_ACCT_AGG_DATE AS
SELECT
    D.UNITDAY UNITDAY,
    AG.ID ACCOUNT_GROUP_ID,
    AG.NAME ACCOUNT_GROUP_NAME,
    A.ID ACCOUNT_ID,
    A.NAME ACCOUNT_NAME,
    AG.TYPE TYPE,
    SUM(T.DEBIT_AMOUNT) CUM_SUM_DEBIT,
    SUM(T.CREDIT_AMOUNT) CUM_SUM_CREDIT
FROM DATEUNIT D
LEFT JOIN TRANSACTION T ON D.UNITDAY >= T.DATEUNIT_UNITDAY
JOIN ACCOUNT A ON T.ACCOUNT_ID = A.ID
JOIN ACCOUNT_GROUP AG ON A.ACCOUNT_GROUP_ID = AG.ID
GROUP BY D.UNITDAY, AG.ID, AG.NAME, A.ID, A.NAME, AG.TYPE
ORDER BY D.UNITDAY, AG.TYPE, AG.NAME, A.NAME;