--SmartFinance\database_engine\src\main\resources\db\migration\
CREATE SEQUENCE IF NOT EXISTS SEQ_INVOICE_V3;
CREATE TABLE INVOICE_V3(
ID BIGINT DEFAULT SEQ_INVOICE_V3.NEXTVAL PRIMARY KEY,
INVOICE_NUMBER VARCHAR(14) NOT NULL,--20160707121201 which 2016-July-07 12:12:01
ORGANIZATION_ID BIGINT,
DATEUNIT_UNITDAY BIGINT,
COMMENT VARCHAR(512) NOT NULL,
DEBIT_TOTAL DECIMAL(10,4) DEFAULT 0,
CREDIT_TOTAL DECIMAL(10,4) DEFAULT 0,
T_CREATEDON TIMESTAMP,
T_UPDATEDON TIMESTAMP,
FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION(ID),
FOREIGN KEY (DATEUNIT_UNITDAY) REFERENCES DATEUNIT(UNITDAY)
);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_UNQ_NVC_NVCNMBR3 ON INVOICE_V3(INVOICE_NUMBER);--for equals/hashcode INVOICE_NUMBER
--The foreign key constraint alone does not provide the index - one must (and should) be created.
--https://asktom.oracle.com/pls/asktom/f?p=100:11:0::::P11_QUESTION_ID:292016138754
--table lock
CREATE INDEX IF NOT EXISTS IDX_NVC_RGNZTND3 ON INVOICE_V3(ORGANIZATION_ID);
CREATE INDEX IF NOT EXISTS IDX_NVC_DTNTNTD3 ON INVOICE_V3(DATEUNIT_UNITDAY);

CREATE TRIGGER T_INVOICE_V3_INS
BEFORE INSERT
ON INVOICE_V3
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerInvoiceV3";

CREATE TRIGGER T_INVOICE_V3_UPD
BEFORE UPDATE
ON INVOICE_V3
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerInvoiceV3";

CREATE TRIGGER T_INVOICE_V3_DEL
BEFORE DELETE
ON INVOICE_V3
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerInvoiceV3";

GRANT SELECT, INSERT, UPDATE, DELETE ON
INVOICE_V3
TO client;