CREATE SEQUENCE SEQ_FAMILY_MEMBER;
CREATE TABLE FAMILY_MEMBER(
ID BIGINT DEFAULT SEQ_FAMILY_MEMBER.NEXTVAL PRIMARY KEY,
NAME VARCHAR(65) NOT NULL,
DESCRIPTION VARCHAR(1024),
T_CREATEDON TIMESTAMP,
T_UPDATEDON TIMESTAMP,
ISDELETED BOOLEAN DEFAULT FALSE
);
CREATE INDEX IF NOT EXISTS IDXFMLMMBRDEL ON FAMILY_MEMBER(ISDELETED);

CREATE TRIGGER T_FAMILY_MEMBER_INS 
BEFORE INSERT 
ON FAMILY_MEMBER 
FOR EACH ROW 
CALL "com.makco.smartfinance.h2db.triggers.TriggerFamilyMember";

CREATE TRIGGER T_FAMILY_MEMBER_UPD 
BEFORE UPDATE 
ON FAMILY_MEMBER 
FOR EACH ROW 
CALL "com.makco.smartfinance.h2db.triggers.TriggerFamilyMember";
