CREATE SEQUENCE IF NOT EXISTS SEQ_CURRENCY;
CREATE TABLE CURRENCY(
ID BIGINT DEFAULT SEQ_CURRENCY.NEXTVAL PRIMARY KEY,
CODE VARCHAR(3) NOT NULL,
NAME VARCHAR(32),
DESCRIPTION VARCHAR(128),
T_CREATEDON TIMESTAMP,
T_UPDATEDON TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_UNQ_CRRNC_CD ON CURRENCY(CODE);--because we order by code

CREATE TRIGGER T_CURRENCY_INS
BEFORE INSERT
ON CURRENCY
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerCurrency";

CREATE TRIGGER T_CURRENCY_UPD
BEFORE UPDATE
ON CURRENCY
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerCurrency";

CREATE TRIGGER T_CURRENCY_DEL
BEFORE DELETE
ON CURRENCY
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerCurrency";
