CREATE SEQUENCE IF NOT EXISTS SEQ_CATEGORY;
CREATE TABLE CATEGORY(
ID BIGINT DEFAULT SEQ_CATEGORY.NEXTVAL PRIMARY KEY,
CATEGORY_GROUP_ID BIGINT,
CATEGORY_GROUP_TYPE VARCHAR(1) NOT NULL,--discriminator: CREDIT/DEBIT category group
NAME VARCHAR(32) NOT NULL,
DESCRIPTION VARCHAR(512),
T_CREATEDON TIMESTAMP,
T_UPDATEDON TIMESTAMP,
FOREIGN KEY (CATEGORY_GROUP_ID,CATEGORY_GROUP_TYPE) REFERENCES CATEGORY_GROUP(ID,TYPE)
);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_UNQ_CTGR_CGIDNM ON CATEGORY(CATEGORY_GROUP_ID,NAME);--because we search by TYPE,NAME

CREATE TRIGGER T_CATEGORY_INS
BEFORE INSERT
ON CATEGORY
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerCategory";

CREATE TRIGGER T_CATEGORY_UPD
BEFORE UPDATE
ON CATEGORY
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerCategory";

CREATE TRIGGER T_CATEGORY_DEL
BEFORE DELETE
ON CATEGORY
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerCategory";
