CREATE SEQUENCE IF NOT EXISTS SEQ_ACCOUNT_GROUP;
CREATE TABLE ACCOUNT_GROUP(
ID BIGINT DEFAULT SEQ_ACCOUNT_GROUP.NEXTVAL PRIMARY KEY,
TYPE VARCHAR(1) NOT NULL,
NAME VARCHAR(32) NOT NULL,
DESCRIPTION VARCHAR(512),
T_CREATEDON TIMESTAMP,
T_UPDATEDON TIMESTAMP
);
--http://stackoverflow.com/questions/179085/multiple-indexes-vs-multi-column-indexes
CREATE UNIQUE INDEX IF NOT EXISTS IDX_UNQ_CCNTGRGRP_TPNM ON ACCOUNT_GROUP(TYPE,NAME);--because we search by TYPE,NAME

CREATE TRIGGER T_ACCOUNT_GROUP_INS
BEFORE INSERT
ON ACCOUNT_GROUP
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerAccountGroup";

CREATE TRIGGER T_ACCOUNT_GROUP_UPD
BEFORE UPDATE
ON ACCOUNT_GROUP
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerAccountGroup";

CREATE TRIGGER T_ACCOUNT_GROUP_DEL
BEFORE DELETE
ON ACCOUNT_GROUP
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerAccountGroup";
