CREATE SEQUENCE IF NOT EXISTS SEQ_ACCOUNT;
CREATE TABLE ACCOUNT(
ID BIGINT DEFAULT SEQ_ACCOUNT.NEXTVAL PRIMARY KEY,
ACCOUNT_GROUP_ID BIGINT,
ACCOUNT_GROUP_TYPE VARCHAR(1) NOT NULL,--discriminator: CREDIT/DEBIT account group
NAME VARCHAR(32) NOT NULL,
DESCRIPTION VARCHAR(512),
T_CREATEDON TIMESTAMP,
T_UPDATEDON TIMESTAMP,
FOREIGN KEY (ACCOUNT_GROUP_ID,ACCOUNT_GROUP_TYPE) REFERENCES ACCOUNT_GROUP(ID,TYPE)
);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_UNQ_CCNTGR_AGIDNM ON ACCOUNT(ACCOUNT_GROUP_ID,NAME);--because we search by TYPE,NAME

CREATE TRIGGER T_ACCOUNT_INS
BEFORE INSERT
ON ACCOUNT
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerAccount";

CREATE TRIGGER T_ACCOUNT_UPD
BEFORE UPDATE
ON ACCOUNT
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerAccount";

CREATE TRIGGER T_ACCOUNT_DEL
BEFORE DELETE
ON ACCOUNT
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerAccount";
