CREATE SEQUENCE IF NOT EXISTS SEQ_INVOICE;
CREATE TABLE INVOICE(
ID BIGINT DEFAULT SEQ_INVOICE.NEXTVAL PRIMARY KEY,
INVOICE_NUMBER VARCHAR(14) NOT NULL,--20160707121201 which 2016-July-07 12:12:01
ORGANIZATION_ID BIGINT,
DATEUNIT_UNITDAY BIGINT,
COMMENT VARCHAR(512) NOT NULL,
SUB_TOTAL DECIMAL(10,4) DEFAULT 0, --before tax
TOTAL DECIMAL(10,4) DEFAULT 0, --after tax
T_CREATEDON TIMESTAMP,
T_UPDATEDON TIMESTAMP,
FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION(ID),
FOREIGN KEY (DATEUNIT_UNITDAY) REFERENCES DATEUNIT(UNITDAY)
);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_UNQ_NVC_NVCNMBR ON INVOICE(INVOICE_NUMBER);--for equals/hashcode INVOICE_NUMBER
--The foreign key constraint alone does not provide the index - one must (and should) be created.
--https://asktom.oracle.com/pls/asktom/f?p=100:11:0::::P11_QUESTION_ID:292016138754
--table lock
CREATE INDEX IF NOT EXISTS IDX_NVC_RGNZTND ON INVOICE(ORGANIZATION_ID);
CREATE INDEX IF NOT EXISTS IDX_NVC_DTNTNTD ON INVOICE(DATEUNIT_UNITDAY);

CREATE TRIGGER T_INVOICE_INS
BEFORE INSERT
ON INVOICE
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerInvoice";

CREATE TRIGGER T_INVOICE_UPD
BEFORE UPDATE
ON INVOICE
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerInvoice";

CREATE TRIGGER T_INVOICE_DEL
BEFORE DELETE
ON INVOICE
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerInvoice";

GRANT SELECT, INSERT, UPDATE, DELETE ON
INVOICE
TO client;