CREATE OR REPLACE VIEW V_ACC_AGG AS
SELECT
    AG.ID ACCOUNT_GROUP_ID,
    AG.NAME ACCOUNT_GROUP_NAME,
    A.ID ACCOUNT_ID,
    A.NAME ACCOUNT_NAME,
    AG.TYPE TYPE,
    SUM(T.DEBIT_AMOUNT) SUM_DEBIT,
    SUM(T.CREDIT_AMOUNT) SUM_CREDIT
FROM ACCOUNT_GROUP AG
JOIN ACCOUNT A ON A.ACCOUNT_GROUP_ID = AG.ID
LEFT JOIN TRANSACTION_V3 T ON T.ACCOUNT_ID = A.ID
GROUP BY AG.ID, AG.NAME, A.ID, A.NAME, AG.TYPE
ORDER BY AG.TYPE, AG.NAME, A.NAME;