CREATE SEQUENCE IF NOT EXISTS SEQ_CATEGORY_GROUP;
CREATE TABLE CATEGORY_GROUP(
ID BIGINT DEFAULT SEQ_CATEGORY_GROUP.NEXTVAL PRIMARY KEY,
TYPE VARCHAR(1) NOT NULL,
NAME VARCHAR(32) NOT NULL,
DESCRIPTION VARCHAR(512),
T_CREATEDON TIMESTAMP,
T_UPDATEDON TIMESTAMP
);
--http://stackoverflow.com/questions/179085/multiple-indexes-vs-multi-column-indexes
CREATE UNIQUE INDEX IF NOT EXISTS IDX_UNQ_CTGRGRP_TPNM ON CATEGORY_GROUP(TYPE,NAME);--because we search by TYPE,NAME

CREATE TRIGGER T_CATEGORY_GROUP_INS
BEFORE INSERT
ON CATEGORY_GROUP
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerCategoryGroup";

CREATE TRIGGER T_CATEGORY_GROUP_UPD
BEFORE UPDATE
ON CATEGORY_GROUP
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerCategoryGroup";

CREATE TRIGGER T_CATEGORY_GROUP_DEL
BEFORE DELETE
ON CATEGORY_GROUP
FOR EACH ROW
CALL "com.makco.smartfinance.h2db.triggers.TriggerCategoryGroup";

GRANT SELECT, INSERT, UPDATE, DELETE ON
CATEGORY_GROUP
TO client;